# -*- coding: utf-8 -*-
"""2: KMeans Intro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1929NJ2elm6Fe0aZ-ZJblsls9nKfiI6-s
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

#data = pd.read_csv('https://github.com/QuarkNet-HEP/coding-camp/raw/refs/heads/main/data/dielectron_with_masses.csv')
data = pd.read_csv('https://github.com/QuarkNet-HEP/coding-camp/raw/refs/heads/main/data/dielectron_minus_bkgd.csv')
data.shape

orig = data.copy()
data = data.loc[data['mass'] < 20].copy()

nbins = 100
plt.hist(data['mass'], bins=nbins, color='black', alpha=.5)
plt.show()

"""Task

The code below which does not produce a very good fit. Work in small groups to adjust parameters to improve results.
"""

kmeans = KMeans(n_clusters=6)
data['label'] = kmeans.fit_predict(data[['mass']])

for i in data['label'].unique():
  plt.hist(data[data['label']==i]['mass'], bins=nbins, alpha=.5, label=i)
plt.legend()

kmeans.cluster_centers_

kmeans.n_iter_

def get_properies(model):
  return [i for i in model.__dict__ if i.endswith('_')]

get_properies(kmeans)



from sklearn.mixture import GaussianMixture
from scipy import stats
from scipy.stats import norm

#reformatting data for fitting
masses = data['mass'].to_numpy().reshape(-1,1)

n_components = 6
gmm = GaussianMixture(n_components=n_components, covariance_type='spherical', n_init=5, tol=1e-5, max_iter=1000, warm_start=False, verbose=2, verbose_interval=100).fit(masses)

x = np.linspace(0,100, num=1000)

for i in range(0, gmm.means_.shape[0]):
  plt.plot(x, 5000*gmm.weights_[i]*stats.norm.pdf(x, gmm.means_[i], gmm.covariances_[i]**0.5))
  plt.vlines(gmm.means_[i],0,2000, colors='grey', linestyles='dotted')
plt.hist(masses, bins=100, alpha=.5)
plt.show()

gmm.means_

# optimization analysis

masses = data['mass'].to_numpy().reshape(-1,1)
x = np.linspace(0,100, num=1000)
n_components = 6

n_trials = 20

perf = pd.DataFrame()
for i in range(0, n_trials):
  gmm = GaussianMixture(n_components=n_components, covariance_type='spherical', tol=1e-3, n_init=5, warm_start=True).fit(masses)
  perf["col" + str(i)] = pd.DataFrame(data=gmm.means_)

for col in perf:
    perf[col] = perf[col].sort_values(ignore_index=True)

plt.plot(perf.transpose())

perf = pd.DataFrame()
for i in range(0, n_trials):
  gmm = GaussianMixture(n_components=n_components, covariance_type='spherical', tol=1e-3, n_init=5).fit(masses)
  perf["col" + str(i)] = pd.DataFrame(data=gmm.means_)

for col in perf:
    perf[col] = perf[col].sort_values(ignore_index=True)

plt.plot(perf.transpose())

gmm.means_

